### ISSUE TITLE
exception on Mac

### ISSUE THREAD

**Issue by ragbear** [DebRC/Algorithm-Visualizer#1]
when I run the code on mac, there is an exception, how do I solve this.
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8180dbf0b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff817e3cb9d objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8181048ca -[NSException raise] + 9
	3   AppKit                              0x00007ff81aab6171 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007ff81aaa1ee6 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1287
	5   AppKit                              0x00007ff81aaa19d9 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libtk8.6.dylib                      0x0000000104688f91 TkMacOSXMakeRealWindowExist + 720
	7   libtk8.6.dylib                      0x0000000104688b93 TkWmMapWindow + 63
	8   libtk8.6.dylib                      0x00000001045ee125 Tk_MapWindow + 158
	9   libtk8.6.dylib                      0x00000001045f6a8b MapFrame + 59
	10  libtcl8.6.dylib                     0x0000000104960171 TclServiceIdle + 75
	11  libtcl8.6.dylib                     0x0000000104944796 Tcl_DoOneEvent + 341
	12  libtk8.6.dylib                      0x000000010467b716 TkpInit + 766
	13  libtk8.6.dylib                      0x00000001045ef387 Initialize + 2402
	14  _tkinter.cpython-39-darwin.so       0x00000001045a76f4 Tcl_AppInit + 84
	15  _tkinter.cpython-39-darwin.so       0x00000001045a204a Tkapp_New + 602
	16  _tkinter.cpython-39-darwin.so       0x00000001045a1971 _tkinter_create + 561
	17  Python                              0x0000000104a7d667 cfunction_vectorcall_FASTCALL + 199
	18  Python                              0x0000000104b2791d call_function + 413
	19  Python                              0x0000000104b24c0e _PyEval_EvalFrameDefault + 28734
	20  Python                              0x0000000104b28856 _PyEval_EvalCode + 2950
	21  Python                              0x0000000104a3a6ed _PyFunction_Vectorcall + 253
	22  Python                              0x0000000104a39e44 _PyObject_FastCallDictTstate + 260
	23  Python                              0x0000000104a3aa7b _PyObject_Call_Prepend + 139
	24  Python                              0x0000000104a9d266 slot_tp_init + 214
	25  Python                              0x0000000104a94794 type_call + 340
	26  Python                              0x0000000104a3a018 _PyObject_MakeTpCall + 376
	27  Python                              0x0000000104b279f2 call_function + 626
	28  Python                              0x0000000104b24cb1 _PyEval_EvalFrameDefault + 28897
	29  Python                              0x0000000104a3a7a3 function_code_fastcall + 163
	30  Python                              0x0000000104b2791d call_function + 413
	31  Python                              0x0000000104b24be1 _PyEval_EvalFrameDefault + 28689
	32  Python                              0x0000000104a3a7a3 function_code_fastcall + 163
	33  Python                              0x0000000104b2791d call_function + 413
	34  Python                              0x0000000104b24be1 _PyEval_EvalFrameDefault + 28689
	35  Python                              0x0000000104a3a7a3 function_code_fastcall + 163
	36  Python                              0x0000000104a3cb83 method_vectorcall + 371
	37  Python                              0x0000000104bcb347 t_bootstrap + 71
	38  Python                              0x0000000104b79ca9 pythread_wrapper + 25
	39  libsystem_pthread.dylib             0x00007ff817f994f4 _pthread_start + 125
	40  libsystem_pthread.dylib             0x00007ff817f9500f thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by DebRC** [comment]
This app was not developed for Mac.

Refer to this -
https://developer.apple.com/forums/thread/123257
